name = "test"
type = "javascript"
compatibility_date = "2022-04-05"

zone_id = ""
account_id = "d64123c31636ef4d17b3c241b16d2051"
route = "test.dev100.workers.dev/*"
workers_dev = true

[site]
bucket = "./public"
entry-point = "build"

[build]

command = "npm i && npm run build"

[build.upload]
format="service-worker"
